[build.env]
passthrough = ["DIOXUS_ASSET_ROOT=app", "PSLINK_IP=0.0.0.0"]

[target.x86_64-unknown-linux-musl]
image = "docker.io/library/alpine:latest"
dockerfile = "cross-x86_64.Dockerfile"

[target.aarch64-unknown-linux-musl]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-musl:main"
dockerfile = "cross-aarch64.Dockerfile"
