[application]


[web.app]

title = "Pslink Kurzlinks"
base_path = "/app/"

[Web.wasm_opt]
level = "s"

[bundle]
identifier = "de.teilgedanken.pslink"
publisher = "Franz Dietrich"
icon = [
    "ui/assets/favicon.svg",
    "ui/assets/favicon.png",
    "ui/assets/favicon.icns",
    "ui/assets/favicon.ico",
]
