[package]
authors = ["Dietrich <dietrich@teilgedanken.de>"]
build = "build.rs"
categories = ["web-programming", "network-programming", "web-programming::http-server", "command-line-utilities"]
description = "A simple webservice that allows registered users to create short links including qr-codes.\nAnyone can visit the shortened links. This is an ideal setup for small busines or for publishing papers."
edition = "2018"
keywords = ["url", "link", "webpage", "actix", "web"]
license = "MIT OR Apache-2.0"
name = "pslink"
readme = "README.md"
repository = "https://github.com/enaut/pslink/"
version = "0.4.4"

[build-dependencies]
actix-web-static-files = { git = "https://github.com/enaut/actix-web-static-files.git", branch="master" }
static-files = { version = "0.2", default-features = false }

[dependencies]
actix-identity = "0.4.0-beta.2"
actix-rt = "2.2"
actix-web = "4.0.0-beta.9"
actix-web-static-files = { git = "https://github.com/enaut/actix-web-static-files.git", branch="master" }
actix-files = "0.6.0-beta.7"
argonautica = "0.2"
clap = "2.33"
dotenv = "0.15.0"
fluent-langneg = "0.13"
image = "0.23"
opentelemetry = "0.16"
opentelemetry-jaeger = "0.15"
qrcode = "0.12"
rand = "0.8"
rpassword = "5.0"
serde = {version="1.0", features = ["derive"]}
static-files = { version = "0.2", default-features = false }
thiserror = "1.0"
tracing-actix-web = "0.4.0-beta.13"
tracing-opentelemetry = "0.15"
async-trait = "0.1"
enum-map = {version="1", features = ["serde"]}
indexmap = "~1.6.2"

pslink-shared = {version="0.4",  path = "../shared" }

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[dependencies.fluent-templates]
version = "0.6"

[dependencies.sqlx]
features = ["sqlite", "macros", "runtime-actix-rustls", "chrono", "migrate", "offline"]
version = "0.5"

[dependencies.tracing]
features = ["log"]
version = "0.1"

[dependencies.tracing-subscriber]
features = ["registry", "env-filter"]
version = "0.2.17"

[dev-dependencies]
actix-server = "1.0.4"
tempdir = "0.3"
test_bin = "0.3"
tokio = "1.12"
assert_cmd = "2.0"
predicates = "2.0.0"


[dev-dependencies.reqwest]
features = ["cookies", "json"]
version = "0.11"
