name: Build and Push ARM64 Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to use (e.g., v1.0.0)'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Version tag to use (e.g., v1.0.0)'
        required: false
        type: string

jobs:
  build-arm64:
    name: Build and push ARM64 Docker image
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      repo-owner: ${{ steps.lowercase_repo.outputs.repo-owner }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set version variable
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" = "workflow_call" ] && [ -n "${{ inputs.version }}" ]; then
            echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
            echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-musl
          override: true

      - name: Install musl-tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install Dioxus CLI
        run: cargo binstall dioxus-cli@0.7.0-alpha.2 -y

      - name: Lowercase repository owner
        id: lowercase_repo
        run: |
          echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr 'A-Z' 'a-z')" >> $GITHUB_ENV
          echo "repo-owner=$(echo ${{ github.repository_owner }} | tr 'A-Z' 'a-z')" >> $GITHUB_OUTPUT

      - name: Create bundle
        run: dx bundle --package web --release --platform web

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push aarch64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./aarch64.Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/pslink:aarch64-latest
            ghcr.io/${{ env.REPO_OWNER }}/pslink:aarch64-${{ env.VERSION }}
