name: Create Multi-Architecture Docker Image

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to use (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build-x86_64:
    name: Build x86_64 image
    uses: ./.github/workflows/build_docker_x86_64.yml
    secrets: inherit

  build-arm64:
    name: Build ARM64 image  
    uses: ./.github/workflows/build_docker_arm64.yml
    secrets: inherit

  create-multiarch:
    name: Create and push multi-arch manifest
    runs-on: ubuntu-latest
    needs: [build-x86_64, build-arm64]
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set version variable
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi

      - name: Lowercase repository owner
        id: lowercase_repo
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr 'A-Z' 'a-z')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push multi-arch manifest
        run: |
          # Create manifest for latest tag
          docker buildx imagetools create -t ghcr.io/${{ env.REPO_OWNER }}/pslink:latest \
            ghcr.io/${{ env.REPO_OWNER }}/pslink:aarch64-latest \
            ghcr.io/${{ env.REPO_OWNER }}/pslink:x86_64-latest
          
          # Create manifest for version tag
          docker buildx imagetools create -t ghcr.io/${{ env.REPO_OWNER }}/pslink:${{ env.VERSION }} \
            ghcr.io/${{ env.REPO_OWNER }}/pslink:aarch64-${{ env.VERSION }} \
            ghcr.io/${{ env.REPO_OWNER }}/pslink:x86_64-${{ env.VERSION }}
