name: Dioxus Fullstack App CI

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      channel:
        required: true
        description: Choose the version number to publish with. Must be a tag (ie v0.4.0)
        type: string

jobs:
  frontend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install Dioxus CLI
        run: cargo binstall dioxus-cli

      - name: Build Dioxus frontend
        run: dx bundle --release --package web

      - name: rename binary
        run: mv target/dx/web/release/web/server target/dx/web/release/web/pslink

      - name: rename path
        run: mv target/dx/web/release/web target/dx/web/release/pslink

      - name: Create archive of build artifacts
        run: tar -czvf pslink-linux-x86_64-bundle.tgz -C target/dx/web/release pslink

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: pslink-linux-x86_64-bundle.tgz
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          generate_release_notes: true

      - name: Upload artifacts (for non-tagged builds)
        uses: actions/upload-artifact@v4
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          name: web-build
          path: target/dx/web/release/pslink