name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
        override: true
    - uses: davidB/rust-cargo-make@v1
      with:
        version: 'latest'
    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: 'latest'
    - uses: actions/checkout@v2
    - name: Install xmllint
      run: sudo apt-get install musl-tools
    - name: Build
      run: cargo make build_standalone