name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
        override: true
    - uses: davidB/rust-cargo-make@v1
      with:
        version: '0.23.0'
    - uses: actions/checkout@v2
    - name: Build
      run: cargo make build_standalone